Fix migration conflict in insights
CommandError: Conflicting migrations detected;
multiple leaf nodes in the migration graph:
(0007_add_section_block, 0007_add_teaser_image in insights).